"""empty message

Revision ID: 349d0742c025
Revises: a1b878edca80
Create Date: 2022-11-07 12:13:41.571303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349d0742c025'
down_revision = 'a1b878edca80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'dept_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
