"""empty message

Revision ID: 90072d975fa5
Revises: 1242e5c8d73f
Create Date: 2022-11-06 13:26:30.341405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90072d975fa5'
down_revision = '1242e5c8d73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'age')
    # ### end Alembic commands ###
