"""empty message

Revision ID: a1b878edca80
Revises: 90072d975fa5
Create Date: 2022-11-06 13:36:40.614305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b878edca80'
down_revision = '90072d975fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('dept_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'departments', ['dept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'dept_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
